version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity

  mongo:
    image: mongo:7.0.4
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
